telegram:
    user: masudur_rahman
database:
    type: sqlite
    sqlite:
        syncToDrive: true
#    postgres:
#        name: expense
#        host: localhost
#        port: 5432
#        user: postgres
#        password: postgres
#        sslmode: disable
