name: Release

on:
    push:
        tags:
            - "*.*"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v3

            - name: Set up QEMU
              id: qemu
              uses: docker/setup-qemu-action@v2

            - name: Setup Go 1.21
              id: go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.21'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Install manifest-tool
              run: |
                  wget https://github.com/estesp/manifest-tool/releases/download/v2.0.8/binaries-manifest-tool-2.0.8.tar.gz
                  mkdir manifest-tool
                  tar -xvzf binaries-manifest-tool-2.0.8.tar.gz -C manifest-tool
                  sudo mv manifest-tool/manifest-tool-linux-amd64 /usr/local/bin/manifest-tool

            - name: Publish Docker image to GitHub Container Registry
              env:
                  REGISTRY: ghcr.io/masudur-rahman
                  DOCKER_TOKEN: ${{ secrets.GH_TOKEN }}
                  USERNAME: masudur-rahman
              run: |
                  docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make release

            - name: Publish Docker image to Docker Container Registry
              env:
                  REGISTRY: masudjuly02
                  SRC_REG: ghcr.io/masudur-rahman
                  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                  USERNAME: masudjuly02
              run: |
                  docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make release
