name: Release

on:
    push:
        tags:
            - "*.*"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build Backend
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: go.mod

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Expose GitHub Actions cache to buildx
              uses: crazy-max/ghaction-github-runtime@v4

            - name: Publish Docker image to GitHub Container Registry
              env:
                  REGISTRY: ghcr.io/masudur-rahman
                  DOCKER_TOKEN: ${{ secrets.GH_TOKEN }}
                  USERNAME: masudur-rahman
                  DOCKER_CACHE_ARGS: --cache-from type=gha --cache-to type=gha,mode=max
              run: |
                  docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make ensure-base
                  make release

            - name: Publish Docker image to Docker Container Registry
              env:
                  REGISTRY: masudjuly02
                  SRC_REG: ghcr.io/masudur-rahman
                  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                  USERNAME: masudjuly02
                  DOCKER_CACHE_ARGS: --cache-from type=gha --cache-to type=gha,mode=max
              run: |
                  docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make ensure-base
                  make release

    build-web:
        name: Build Web Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v7

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Push web image to GitHub Container Registry
              env:
                  REGISTRY: ghcr.io/masudur-rahman
                  DOCKER_TOKEN: ${{ secrets.GH_TOKEN }}
                  USERNAME: masudur-rahman
              run: |
                  docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make docker-push-web

            - name: Push web image to Docker Container Registry
              env:
                  REGISTRY: masudjuly02
                  DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
                  USERNAME: masudjuly02
              run: |
                  docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
                  make docker-push-web
